spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/cargo_portal
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp   
  thymeleaf:
    enabled: false
server:
  port : 8080
  
